!****************************************************************************
!
!  LOCAL SEISMIC RESPONSE OF SURFACE GRANULAR
!
!  SUBROUTINE LOCSEISMIC: 
!
!****************************************************************************

	SUBROUTINE LOCSEISMIC()

	USE DFPORT
	USE GLOBAL
	 
	IMPLICIT NONE

	INTEGER :: I, J, K, FSN, CNT, STS, LOVE, HATE, L
	INTEGER, ALLOCATABLE :: FSET(:)
	DOUBLE PRECISION :: X, PT(2)
	DOUBLE PRECISION :: Q(3), QN(3), QD(3)
	CHARACTER (LEN=6) :: STR

	CNT=0

	OPEN(UNIT=234,FILE='INITIAL_STATE.TXT',STATUS='OLD')

	

    DO L=1,1000

	  MODE=1

	  LOVE=0

	  READ(234,*)MM, INITIAL_FACENUM, INITIAL_SIDENUM, INITIAL_U,&
			     INITIAL_V,INITIAL_X,INITIAL_Y, INITIAL_Z,&
			     INITIAL_DX, INITIAL_DY, INITIAL_DZ

	  ID(1)=INITIAL_FACENUM
      ID(2)=INITIAL_SIDENUM

	  ORBINI(1)=INITIAL_X
	  ORBINI(2)=INITIAL_Y
	  ORBINI(3)=INITIAL_Z
	  ORBINI(4)=INITIAL_DX
	  ORBINI(5)=INITIAL_DY
	  ORBINI(6)=INITIAL_DZ

	  

	  SIDX=0

	  CALL ODESLVR
  
	  IF (SIDX.EQ.1) THEN

		CALL GLPATH
		CNT=CNT+1
		WRITE(STR,'(I6)') CNT
	    STS=RENAME('MOTOLOG.TXT','MOTOLOG'//TRIM(ADJUSTL(STR))//'.BT')
	    STS=RENAME('GLPATH.TXT','GLPATH'//TRIM(ADJUSTL(STR))//'.BT')
		WRITE(*,*) CNT
		  		  
      ENDIF


	  
    END DO

	RETURN

	END SUBROUTINE LOCSEISMIC