!****************************************************************************
!
!  MODULE GLOBAL: 
!
!****************************************************************************

	MODULE GLOBAL

	IMPLICIT NONE

	!THE PARAMETERS PERMITTED TO SET, UNIT: KG, KM, S

    CHARACTER(20) :: FILENAME="RYUGU.TXT"

	DOUBLE PRECISION, PARAMETER :: DENSITY=1.19D12,G=6.67259D-20,PI=3.14159265358979323846D0,PERIOD=27457.2D0     !!18802.8D0

	!RULERS FOR NORMALIZATION, SRULER: KM, TRULER: S, KAPPA: UNITLESS 

	DOUBLE PRECISION :: SRULER, TRULER, KAPPA

	!POLYHEDRON GRAVITY FIELD BASIC DATA

	INTEGER :: N_V,N_E,N_F

	DOUBLE PRECISION, ALLOCATABLE :: V_DATA(:,:),NE_DATA(:,:),LE_DATA(:),NF_DATA(:,:)

	INTEGER,ALLOCATABLE :: E_DATA(:,:),F_DATA(:,:),SEC_DATA(:,:,:)

	!MASS GEOMETRY DATA

	DOUBLE PRECISION :: T0,T1(3),T2(6),MASS,RC0(3),JMX0(3,3),JMX(3,3)

	END MODULE GLOBAL
